
let button = document.querySelector("button")
let body = document.querySelector("body")
// body. style. backgroundColor = "white"

button.addEventListener("click", () =>{
    if(body. style. backgroundColor === "white"){
        body. style. backgroundColor = "black";
        body. style. backgroundColor = "black"
    }else{
        body. style. backgroundColor = "black";
        body. style. backgroundColor = "white"
    }

})